Add arch migration
conda-forge/perl-encode-feedstock pull request #5
Opened 2024-09-10 08:40 UTC by martin-g

Based on top of https://github.com/conda-forge/perl-encode-feedstock/pull/4

* Uses Azure CI for PPC64LE (cross-compilation) because TravisCI often fails to provide a PPC64LE native node.
* Fix lint issues (`stdlib('c')`)

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2024-09-10 08:41 UTC, martin-g commented
@conda-forge-admin, please rerender

2024-09-10 08:50 UTC, martin-g commented
The PPC64LE build won't work because of:
```
Encountered problems while solving:
  - nothing provides requested perl-storable
```
I'll exclude it!

2024-09-10 08:51 UTC, martin-g commented
@conda-forge-admin, please rerender

2024-09-10 09:00 UTC, martin-g commented
@conda-forge-admin, please ping team
Please review!

2024-09-10 10:07 UTC, xileF1337 requested changes

2024-09-10 10:07 UTC, xileF1337 commented on recipe/meta.yaml
> +    - {{ stdlib("c") }}
Could you please use a consistent quotation style for these template directives (either double " " or single ' ', I'm fine with either)? Thank you!

2024-09-10 10:32 UTC, martin-g commented on recipe/meta.yaml
> +    - {{ stdlib("c") }}
Done!

2024-09-10 10:32 UTC, martin-g commented
@conda-forge-admin, please rerender

2024-10-06 20:33 UTC, xileF1337 approved these changes

2024-10-06 20:33 UTC, merged